name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt install yarn
      
    - name: Install palava-web
      run: yarn install --frozen-lockfile

    - name: Lint palava-web
      run: yarn lint
    
    - name: Audit palava-web
      run: yarn audit --groups dependencies
